---
- name: install some stuff
  hosts: webservers
  remote_user: vagrant
  become: yes

  tasks:
  - name: lets install epel
    yum: name=epel-release state=present

  - name: install python binding for selinux
    yum: name={{item}} state=present
    with_items:
    - libselinux-python
    - libselmanage-python

  - name: test to see if selinux is running
    command: getenforce
    register: sestatus
    changed_when: false

  - name: install apache
    yum: name=httpd state=present

  - name: test to see if apache is running
    service: name=httpd state=started enabled=yes
